#! /bin/sh

# bspc rule for assigning the values to the workspaces in the status bar
bspc monitor -d 1 2 3 4 5 6

# bspc rules for border width
bspc config border_width         4

# bspc rules for window gaps
bspc config window_gap          14
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule to change focus to follow the mouse pointer
bspc config focus_follows_pointer true

# bspc border configs
bspc config active_border_color '#0C1115'
bspc config normal_border_color '#0C1115'
bspc config focused_border_color '#928374'

#bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a thunderbird-default desktop='^2'
bspc rule -a Spotify desktop='^3'
bspc rule -a Code desktop='^4'
bspc rule -a Gimp desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# start SXHKD at launch
pgrep -x sxhkd > /dev/null || sxhkd &

# start Picom at launch
picom &

# start Feh at launch
feh --bg-fill /home/scott/Pictures/Wallpapers/coffee01.jpeg &

# start Polybar script at launch
/home/scott/.config/polybar/polybar.launch.sh

# Launch XRandr at launch
xrandr --output DP-6 --mode 2560x1440 --rate 144 &

# start Redshift at launch
redshift &
